# Configuration pour Streamlit Cloud
[theme]
primaryColor = "#FF6B35"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[server]
runOnSave = false
allowRunOnSave = false
port = 8501

[browser]
gatherUsageStats = false

[global]
developmentMode = false

[client]
caching = true

[runner]
magicEnabled = true
installTracer = false

[logger]
level = "info"
